- docs/neovim.md
Hi, just made a few updates on the suggested setup for minuet.
`stream = true` would make sense for most of the average users. And `after_cursor_filter_length` is still occasionally needed, even though really rare, but sometimes FIM would still repeat the code content in suffix.
Also some fixup.
> doc: update minuet-ai.nvim setup.

- lua/vectorcode/integrations/codecompanion.lua
Some non-value adding tweaks to ensure that the parameters for the tool outputs are up to date. I've added some minor QOL features like passing in the xml2lua library as a parameter in the `schema` table. Also, the `output.error` table can also receive `stdout` data (if any; but this requires you to update CodeCompanion).
> refactor: update params to match new CodeCompanion tools

- lua/vectorcode/integrations/copilotchat.lua
- Uses the standard context format expected by CopilotChat
- Improves query handling and error reporting
- Adds guidance text for retrieving repository information
- Uses async apis instead of sync ones inside of plenary.async context
This update aligns with CopilotChat's current context API design.
```lua
require('CopilotChat').setup({
contexts = {
vectorcode = require('vectorcode.integrations').copilotchat.make_context(),
}
})
```
> refactor: improve CopilotChat integration

- doc/VectorCode.txt
- docs/neovim.md
- lua/lsp/vectorcode_server.lua
- lua/vectorcode/cacher/lsp.lua
- lua/vectorcode/config.lua
- lua/vectorcode/jobrunner/init.lua
- lua/vectorcode/jobrunner/lsp.lua
Waiting for [neovim package](https://archlinux.org/packages/extra/x86_64/neovim/) to build...
> feat(nvim)!: use new LSP APIs introduced in nvim 0.11.0

- pyproject.toml
https://github.com/pypa/wheel/blob/0.45.1/src/wheel/macosx_libfile.py this file is removed in `wheel==0.46.0`, which caused issue when building chroma-hnswlib.
> fix(cli): pin `wheel` version to fix broken installation for MacOS.

- src/vectorcode/cli_utils.py
- src/vectorcode/subcommands/vectorise.py
- tests/subcommands/test_vectorise.py
- tests/test_cli_utils.py
- tests/test_main.py
Sometimes, a lot of the code of a project is in hidden files. There's no reason why they shouldn't be vectorised too!
As a real example, some people use GNU Stow to manage their dotfiles, and a lot of dotfiles are hidden files. For example, [my own dotfiles](https://github.com/jpmelos/dotfiles) have a lot of hidden files (and files inside a hidden directory like `.config`). I use AI assistants when working on my dotfiles constantly (especially when writing Lua code to customize Neovim). I need them to be vectorised if I want to use VectorCode while working on my own dotfiles using CodeCompanion.
(By the way, thanks for VectorCode! And for writing an integration with CodeCompanion!)
> Allow vectorising hidden files

- docs/cli.md
- src/vectorcode/cli_utils.py
- src/vectorcode/subcommands/init.py
- src/vectorcode/subcommands/vectorise.py
- tests/subcommands/test_init.py
- tests/subcommands/test_vectorise.py
> feat(cli): global file specs support

- lua/vectorcode/integrations/codecompanion.lua
This PR adds an option that check the existing references that have been added to the chat, and excluding them from further queries. This helps saving tokens, and should help the search if previous queries missed the appropriate documents.
> feat(nvim): avoid retrieving files that is already present in the context

- docs/cli.md
By default pytorch pulls all the cuda dependencies, ending up with a ~5GB virtualenv created by pipx. If you want to use this as a neovim plugin you can have a much more lightweight installation by using cpu-only pytorch
> Document how to install CPU only

- docs/cli.md
- pyproject.toml
- src/vectorcode/chunking.py
- src/vectorcode/cli_utils.py
- src/vectorcode/subcommands/vectorise.py
- tests/test_chunking.py
- tests/test_cli_utils.py
This can be configured by `encoding` option in the json.
Need to decide what to do with mixed-encoding repos (maybe ditch the config option approach and use [this](https://charset-normalizer.readthedocs.io/en/latest/index.html)?).
> feat(cli) : add alternative (non-utf8) encoding support.

- lua/codecompanion/_extensions/vectorcode/init.lua
https://github.com/olimorris/codecompanion.nvim/pull/1290
example config:
```lua
opts = {
extensions = {
vectorcode = {
opts = { add_tools = true, add_slash_command = true },
},
},
},
```
> feat(nvim): use codecompanion extension API.

- docs/cli.md
- pyproject.toml
- src/vectorcode/cli_utils.py
- src/vectorcode/lsp_main.py
- src/vectorcode/mcp_main.py
- tests/test_cli_utils.py
- tests/test_lsp.py
This allows trailing comma, comments (`//`) and more!
With this PR, you can use json5 syntax directly in your `config.json` files. To make your editor (syntax checkers) happy, you may also rename the json to `config.json5` so that the linters will pick up the correct grammar.
> feat(cli): accept json5 config.

- src/vectorcode/chunking.py
- tests/test_chunking.py
Code:
```lua
-- example.lua
local a = 1
local b = 2
local function foo_bar()
local x = 1
local y = 3
local z = 5
return x + y + z
end
```
Before:
```json5
// vectorcode chunks -c 25 example.lua
[
[
"local a = 1local b = 2",
"localfunction foo_bar ()",
"local x = 1local y = 3",
"local z = 5",
"return x + y + z",
"end"
]
]
```
After:
```json5
// vectorcode chunks -c 25 example.lua
[
[
"local a = 1\nlocal b = 2",
"local function foo_bar ()",
"local x = 1\nlocal y = 3",
"local z = 5",
"return x + y + z",
"end"
]
]
```
> fix(cli): preserve spaces and newlines in treesitter chunking.

- docs/cli.md
- src/vectorcode/cli_utils.py
- src/vectorcode/main.py
- src/vectorcode/subcommands/hooks.py
- src/vectorcode/subcommands/init.py
- tests/subcommands/test_hooks.py
- tests/subcommands/test_init.py
most of the times, hooks only need to be set up once for each repo, so it makes sense to merge it with `init`.
> refactor(cli): Merge hooks subcommand into init

- lua/vectorcode/integrations/codecompanion/func_calling_tool.lua
- lua/vectorcode/integrations/codecompanion/legacy_tool.lua
This PR tuned the system prompt so that the model _shouldn't_ include the `<path> </path>` tags in the answer.
This also added the project_root to the tool output presented to the user, so that users have a better idea about whether the tool call was appropriate when performing joint search.
> feat(nvim): tuned system prompt and added project_root to the tool output.

- docs/cli.md
- src/vectorcode/cli_utils.py
- src/vectorcode/common.py
- src/vectorcode/main.py
- tests/subcommands/test_vectorise.py
- tests/test_cli_utils.py
- tests/test_common.py
This allows users to use a chromadb server behind a reverse proxy (`http://your.host.name:8000/your/chroma`) and/or chromadb with HTTPS encryption (`https://your.host.name:8001`). The updated documentation will also address #140. 
This PR supercedes #142 .
> refactor(cli): use `db_url` to replace `host` and `port`.

- lua/vectorcode/integrations/codecompanion/func_calling_tool.lua
ref: https://platform.openai.com/docs/guides/structured-outputs/supported-schemas?api-mode=chat#all-fields-must-be-required
> fix(nvim): correct the tool schema and make all fields required. Fix #133.

- lua/vectorcode/init.lua
- lua/vectorcode/jobrunner/cmd.lua
This PR refactors the neovim plugin for #144  .
Note: jobrunners currently don't provide a status code, which makes it difficult to migrate `check`. The reason is mostly about the LSP runner and will be addressed in future updates.
> refactor(nvim): refactor more APIs to use `jobrunner`.

- docs/cli.md
- src/vectorcode/common.py
- tests/test_common.py
This should help mitigate (though may not fully fix) #24.
> feat(cli): set the default `hnsw:M` value to 64

- lua/vectorcode/cacher/default.lua
- lua/vectorcode/cacher/init.lua
- lua/vectorcode/cacher/lsp.lua
- lua/vectorcode/init.lua
- lua/vectorcode/jobrunner/cmd.lua
- lua/vectorcode/jobrunner/init.lua
- lua/vectorcode/jobrunner/lsp.lua
- src/vectorcode/lsp_main.py
- tests/test_lsp.py
This PR aims to eliminate all usage of `vim.system` and/or `plenary.job` outside of jobrunners.
Also, this PR improved error handling of the LSP server so that the error codes follow the LSP specification.
> refactor(cli, nvim): add exit code to job runners.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- doc/VectorCode.txt
- docs/cli.md
- docs/neovim.md
- Suggest `uv` as the package manager.
> Documentation updates

- src/vectorcode/chunking.py
- src/vectorcode/subcommands/chunks.py
- tests/subcommands/test_chunks.py
- tests/test_chunking.py
Fix #146 
Prerequisite of #168
> Handle line ranges for `StringChunker`

- .github/workflows/panvimdoc.yml
- doc/VectorCode-cli.txt
Allows users to run `:h VectorCode-cli` in nvim to view the CLI docs.
> Bundle CLI documentation into the neovim plugin doc directory

- src/vectorcode/subcommands/update.py
- src/vectorcode/subcommands/vectorise.py
- tests/subcommands/test_vectorise.py
This PR stores the file hashes into the metadata.
On a supported collection, VectorCode will now compare the file hash and the hash stored in the database. If they're the same, they're considered to be the same file (unchanged), and the vectorisation will be skipped for this file.
> Check for file changes (by sha256 hash) before vectorising

- doc/VectorCode.txt
- docs/neovim.md
- lua/vectorcode/integrations/codecompanion/common.lua
- lua/vectorcode/integrations/codecompanion/func_calling_tool.lua
- lua/vectorcode/types.lua
Continuation of #168 , with some refactoring that make the codebase better organised as a prep for #172
> Allow the codecompanion tool to send chunks instead of full documents.

- src/vectorcode/subcommands/init.py
- tests/subcommands/test_init.py
The `init` subcommand didn't copy the global `config.json5`. This PR fixes the issue.
> Copy global `config.json5` during init

- doc/VectorCode.txt
- docs/neovim.md
- lua/vectorcode/config.lua
Since nvim-lspconfig has migrated to use `lsp/`, we can safely drop the old syntax for configuring the LSP.
> Drop support for nvim-lspconfig and only use `vim.lsp.config`.

- src/vectorcode/cli_utils.py
- tests/test_cli_utils.py
> Fix shtab generation for zsh and add tests for it. Fix #211

- pyproject.toml
See https://github.com/chroma-core/chroma/issues/4966
Since we're still using chromadb `0.6.3`, we'd have to do it ourselves.
> Pin posthog to `<6.0.0`

- lua/vectorcode/integrations/codecompanion/query_tool.lua
Deduplication doesn't play very nicely with summarysation due to the following:
1. it prevents the LLM requesting the same results without summarisation;
2. the summariser doesn't always produce the summary. Its system prompt instructs it to optimise the summary based on the query. When deduplication is on, the main chat LLM won't be able to see these.
Therefore, I'm disabling deduplication when summarisation is enabled.
> Disable deduplication for summary mode

- doc/VectorCode.txt
- docs/neovim.md
- lua/vectorcode/integrations/heirline.lua
- lua/vectorcode/integrations/init.lua
- lua/vectorcode/integrations/lualine.lua
Closes #225 .
The heirline component is accessible via the following snippet:
```lua
require("vectorcode.integrations").heirline({ 
show_job_count = true,
component_opts = {
-- put other field of the components here.
-- they'll be merged into the final component.
},
})
```
> Add heirline component

- lua/vectorcode/integrations/codecompanion/query_tool.lua
This PR allows the LLM to turn off the deduplication temporarily.
> Add `deduplicate` parameter to query tool

- doc/VectorCode-cli.txt
- docs/cli.md
- src/vectorcode/cli_utils.py
- src/vectorcode/subcommands/vectorise.py
- tests/subcommands/test_vectorise.py
- tests/test_cli_utils.py
> Support loading `.gitignore` from nested repo/submodules

- lua/vectorcode/integrations/codecompanion/ls_tool.lua
- lua/vectorcode/integrations/codecompanion/vectorise_tool.lua
This PR refactors the codecompanion tools to use hardcoded schema descriptions so that they don't call the `vectorcode prompts` command.
Closes #243 .
@musaffa, please give this a try and lmk if it make the loading faster.
> Update tool descriptions for better loading time

- docs/cli.md
square brackets are used for pattern matching, so they should be quoted.
> Quote square brackets

- pyproject.toml
[The upstream build issue on aarch64 linux](https://github.com/tree-sitter/py-tree-sitter/pull/393) has been resolved.
> Allow `py-tree-sitter>0.25.0`

- lua/vectorcode/integrations/codecompanion/files_ls_tool.lua
- lua/vectorcode/integrations/codecompanion/files_rm_tool.lua
- lua/vectorcode/integrations/codecompanion/init.lua
- lua/vectorcode/integrations/codecompanion/ls_tool.lua
- lua/vectorcode/integrations/codecompanion/query_tool.lua
- lua/vectorcode/integrations/codecompanion/vectorise_tool.lua
- `references` to `context`
- `CodeCompanion.Agent` to `CodeCompanion.Tools`
> Remove outdated API in codecompanion.nvim extension

- lua/vectorcode/integrations/codecompanion/common.lua
- lua/vectorcode/integrations/codecompanion/files_ls_tool.lua
- lua/vectorcode/integrations/codecompanion/ls_tool.lua
- lua/vectorcode/integrations/codecompanion/query_tool.lua
- lua/vectorcode/integrations/codecompanion/vectorise_tool.lua
Closes #260 
Since other tools in codecompanion.nvim are designed to avoid IO on files outside of `cwd`, this PR differentiate paths inside of `cwd` and outside of `cwd` by using relative paths for the former, and absolute paths for the later. Instructions are included in the `query` and `files_ls` tool schemas so that the model knows that they can't use the other tools on files represented by absolute paths.
Until the upstream rule of "no IO outside of `cwd`" is changed, this extension will stick to this rule when formatting the output.
> Handle relative paths for codecompanion tools

- .github/workflows/panvimdoc.yml
- doc/VectorCode-cli.txt
- docs/cli.md
- src/vectorcode/lsp_main.py
- tests/test_lsp.py
This is part of the plan to move the LSP server options to the standard LSP settings (like `vim.lsp.config`).
> Support using LSP workspace folder as default project root for the LSP server.

- lua/vectorcode/integrations/codecompanion/files_ls_tool.lua
- lua/vectorcode/integrations/codecompanion/files_rm_tool.lua
- lua/vectorcode/integrations/codecompanion/query_tool.lua
- lua/vectorcode/integrations/codecompanion/vectorise_tool.lua
This PR refactors the codecompanion.nvim tool schemas so that they don't mark all arguments as `required`. This should make the parameters more comprehensive for the LLMs to understand, and avoid confusions when they want to just use the default values.
Relevant discussion: #272
> Relax schema requirements for CodeCompanion tools (closes #273)

- doc/VectorCode-cli.txt
- docs/cli.md
- src/vectorcode/cli_utils.py
- tests/test_cli_utils.py
It's been observed that the `NaiveReranker` outperforms the default `CrossEncoderReranker` model in a lot of scenarios. While the cross encoders might have more potential, it doesn't provide a good OOTB experience (and changing them won't break anything). Thus, I'm reverting the default reranker to `NaiveReranker`, which is faster, less computationally intensive and more consistent for 0-config usage.
> Revert the default reranker to `NaiveReranker`.

- lua/vectorcode/integrations/codecompanion/query_tool.lua
- lua/vectorcode/types.lua
This is a follow-up of https://github.com/olimorris/codecompanion.nvim/discussions/2030, which introduces ACP adapters alongside the regular HTTP adapters. Since the ACP adapters don't share the same interface as the HTTP adapters, it's easier to only allow HTTP adapters to be used here. This is mostly a fail-safe, because the ACP adapters don't use the codecompanion tools OOTB (?).
> Only allow HTTP adapters for codecompanion result summarisation

- src/vectorcode/chunking.py
- src/vectorcode/mcp_main.py
- src/vectorcode/subcommands/query/__init__.py
- src/vectorcode/subcommands/query/reranker/base.py
- src/vectorcode/subcommands/query/reranker/cross_encoder.py
- src/vectorcode/subcommands/query/reranker/naive.py
- src/vectorcode/subcommands/query/types.py
- src/vectorcode/subcommands/vectorise.py
- tests/subcommands/query/test_query.py
- tests/subcommands/query/test_reranker.py
- tests/subcommands/query/test_types.py
- tests/subcommands/test_chunks.py
- tests/test_mcp.py
> Implement `QueryResult` type.

- lua/vectorcode/integrations/codecompanion/common.lua
- lua/vectorcode/integrations/codecompanion/query_tool.lua
- Enhanced flatten_table_to_string to filter out empty error messages
- Added logic to distinguish actual errors from empty stderr output
- Prevents false error reporting when VectorCode operations succeed but have no stderr
- Provides meaningful fallback error message for truly empty error conditions
- Fixes issue where successful operations with empty stderr were reported as { "" } errors
Resolves the confusing empty error message issue in CodeCompanion integration.
> fix(codecompanion): improve error handling for empty stderr output
